In [1]:
import numpy as np
a=np.random.rand(5) #this is not used coz  of its shape


In [2]:
print(a)


[0.31128238 0.18269104 0.6873313  0.85710652 0.68930795]


In [3]:
print(a.shape)   #shape will be of form 5 or n or rank1 type so not used 


(5,)


In [4]:
print(a.T)

[0.31128238 0.18269104 0.6873313  0.85710652 0.68930795]


In [5]:
print(np.dot(a,a.T))   #dot product of a and a-transpose matrix

1.8124741076172346


In [6]:
#following method is used in neural networks : we jsut donot use data-structures 
#where shape is 5 or n or rank1 arrray instead set a as(5,1)
#rank 1 array doesnt behave as a row-vector or column vector so it is of no use
a=np.random.rand(5,1)
print(a)


[[0.43216593]
 [0.20901994]
 [0.24998872]
 [0.12966945]
 [0.47044828]]


In [7]:
print(a.T)


[[0.43216593 0.20901994 0.24998872 0.12966945 0.47044828]]


In [8]:
print(np.dot(a,a.T))  # the outer product of the vector will give a matrix

[[0.18676739 0.0903313  0.10803661 0.05603872 0.20331172]
 [0.0903313  0.04368934 0.05225263 0.0271035  0.09833307]
 [0.10803661 0.05225263 0.06249436 0.0324159  0.11760677]
 [0.05603872 0.0271035  0.0324159  0.01681417 0.06100277]
 [0.20331172 0.09833307 0.11760677 0.06100277 0.22132159]]


In [15]:
#(5,1) is a column vector while (1,5) is a row-vector
# assert(a.shape==(5,1))  to check if the a vector is (5,1)
#a=a.reshape((5,1))  to convert(1,5) into (5,1) or vice-versa
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)
print("\n")
print(np.dot(a,b)) 

[[-1.82634540e-04  3.96814434e-03 -2.32052269e-03]
 [-2.12585190e+00 -1.55114967e-01  5.70383790e-01]
 [-7.08562478e-01 -7.53840899e-02  2.06321006e-01]]


[[1.05727824]
 [0.1085646 ]
 [0.04267291]]


In [18]:
#concept: the sizes actually match because of broadcasting. b (column vector) is copied 
#3 times so that it can be summed to each column of a.
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(a)
print("\n")
print(b)  #by broadcasting 
print("\n")
print(c)
print("\n")

[[ 0.41000823  1.24617237 -0.31262597]
 [-0.83245037  0.8343915  -1.29487432]]


[[0.80496604]
 [1.14984325]]


[[ 1.21497427  2.0511384   0.49234006]
 [ 0.31739288  1.98423475 -0.14503106]]




In [19]:
#example 
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

#In numpy the "*" operator indicates element-wise multiplication.
#It is different from "np.dot()". If you would try "c = np.dot(a,b)" you would get c.shape = (4, 2).
#Also, the broadcasting cannot happen because of the shape of b. b should have been something like (4, 1) or
#(1, 3) to broadcast properly. So a*b leads to an error!

print(a)
print("\n")
print(b)  
print("\n")
print(c)
print("\n")

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [20]:
#example

a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(a)
print("\n")
print(b)  
print("\n")
print(c)
print("\n")

#remember that a np.dot(a, b) has shape 
#(number of rows of a, number of columns of b). The sizes match because :
#"number of columns of a = 150 = number of rows of b"

[[-0.44368972  0.79780191 -2.3522246  ...  1.55417556  0.59398319
  -0.2928074 ]
 [-1.41319213 -0.06703641 -0.62204831 ... -2.1139162  -1.05448383
   1.28416882]
 [ 0.08467723  0.24726346  0.35091409 ...  0.29371205 -1.13154961
   0.94804277]
 ...
 [ 1.0393801   0.65020766  1.81028383 ... -1.58886738  0.58064531
  -0.66417759]
 [-0.16665242  1.19015613  0.07945274 ... -0.29488677 -0.22046206
  -1.60875926]
 [-0.02201011  1.22718494 -0.44590624 ...  0.25798458  1.6689966
  -0.18943467]]


[[ 1.52012679 -0.77196814  1.75103737 ...  0.94800222 -0.77638614
  -0.39733841]
 [ 0.28436976 -1.19265965 -1.72080592 ... -0.02909902  0.95822981
  -0.41299379]
 [ 0.98118046 -0.49188651  0.67794532 ... -0.73257546 -1.07325466
   1.02113827]
 ...
 [-0.54328919 -0.6292134   1.48745002 ...  1.11622811 -0.98944709
  -2.39710539]
 [-0.07138378  0.33166917 -0.57320893 ... -0.89618271 -0.25731599
  -0.26855469]
 [ 0.10010036  0.69490271  1.04477487 ... -0.85423867  1.65727763
   1.99586932]]


[[ -1.5737999

In [22]:
#example
# a.shape = (3,4)
# b.shape = (4,1)

a = np.random.randn(3, 4)
b = np.random.randn(4, 1)
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]
print(a)
print("\n")
print(b)  
print("\n")
print(c)
print("\n")    

[[ 0.90231001 -0.65110284  1.44344774  0.8389411 ]
 [-1.42090193  0.66587421  1.02974513 -0.3972102 ]
 [-1.23454236  1.62311821 -0.44029592 -0.48099587]]


[[ 0.10838365]
 [ 0.5221672 ]
 [-0.09411749]
 [ 0.36820452]]


[[  1.01069366  -0.12893563   1.34933026 ...  14.91051372  36.19041035
  -20.0422563 ]
 [ -1.31251829   1.18804141   0.93562765 ...  -9.72885366   9.53227435
   -5.93083066]
 [ -1.12615871   2.14528541  -0.53441341 ...   1.76449611   6.96917256
    2.01479194]
 ...
 [ -1.95438685  24.01288467 -19.18888035 ...   9.90554135  -4.86156578
   17.85322071]
 [ -3.50232952   4.26534509  -5.60103458 ...  -6.43220947  -4.5809534
    6.43380101]
 [-12.82302716  -7.81525698 -10.91595384 ...  -3.78908063   6.03118941
    3.59977384]]




In [23]:
#concept
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


In [24]:
# example of vector operation
x = np.array([1, 2, 3])
print (x + 3)

[4 5 6]


In [25]:
# GRADED FUNCTION: basic_sigmoid

import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s = 1/(1+math.exp(x))
    ### END CODE HERE ###
    
    return s
basic_sigmoid(3)

0.04742587317756678

In [26]:
#Actually, we rarely use the "math" library in deep learning because the inputs of the functions are real numbers. In deep learning we mostly
#use matrices and vectors. This is why numpy is more useful. 
#### One reason why we use "numpy" instead of "math" in Deep Learning ###
x = [1, 2, 3]
basic_sigmoid(x) # you will see this give an error when you run it, because x is a vector.

TypeError: must be real number, not list

In [28]:
#topic:
#Any time you need more info on a numpy function, we encourage you to look at [the official documentation](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.exp.html). 

#You can also create a new cell in the notebook and write `np.exp?` (for example) to get quick access to the documentation.

#**Exercise**: Implement the sigmoid function using numpy. 

#**Instructions**: x could now be either a real number, a vector, or a matrix. The data structures we use in numpy to represent these shapes (vectors, matrices...) are called numpy arrays.

In [29]:
# GRADED FUNCTION: sigmoid

import numpy as np # this means you can access numpy functions by writing np.function() instead of numpy.function()

def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s = 1/(1+np.exp(x))
    ### END CODE HERE ###
    
    return s
x = np.array([1, 2, 3])
sigmoid(x)

array([0.26894142, 0.11920292, 0.04742587])

In [30]:
#topic
#### 1.2 - Sigmoid gradient

#As you've seen in lecture, you will need to compute gradients to optimize loss functions using backpropagation. Let's code your first gradient function.

#**Exercise**: Implement the function sigmoid_grad() to compute the gradient of the sigmoid function with respect to its input x. The formula is: $$sigmoid\_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$
#You often code this function in two steps:
#1. Set s to be the sigmoid of x. You might find your sigmoid(x) function useful.
#2. Compute $\sigma'(x) = s(1-s)$

In [31]:
# GRADED FUNCTION: sigmoid_derivative

def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    s = sigmoid(x)
    ds = s/(1-s)
    ### END CODE HERE ###
    
    return ds

In [32]:
x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [0.36787944 0.13533528 0.04978707]


In [33]:
#1.3 - Reshaping arrays
#Two common numpy functions used in deep learning are np.shape and np.reshape().

#X.shape is used to get the shape (dimension) of a matrix/vector X.
#X.reshape(...) is used to reshape X into some other dimension.
#For example, in computer science, an image is represented by a 3D array of shape  (length,height,depth=3)(length,height,depth=3) .
#However, when you read an image as the input of an algorithm you convert it to a vector of shape  (length∗height∗3,1)(length∗height∗3,1) .
#In other words, you "unroll", or reshape, the 3D array into a 1D vector.

#Exercise: Implement image2vector() that takes an input of shape (length, height, 3) and returns a vector of shape (length*height*3, 1). 
#For example, if you would like to reshape an array v of shape (a, b, c) into a vector of shape (a*b,c) you would do:

#v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) 
# (where, v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c)
#Please don't hardcode the dimensions of image as a constant. Instead look up the quantities you need with image.shape[0], etc.


In [34]:
# GRADED FUNCTION: image2vector
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    v=image
    v = v.reshape((v.shape[0]*v.shape[1]*v.shape[2],1))
    ### END CODE HERE ###
    
    return v

In [35]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [36]:
#topic
#1.4 - Normalizing rows
#Another common technique we use in Machine Learning and Deep Learning is to normalize our data. 
#It often leads to a better performance because gradient descent converges faster after normalization. Here, 
#by normalization we mean changing x to  x∥x∥x∥x∥  (dividing each row vector of x by its norm).

#**Exercise**: Implement normalizeRows() to normalize the rows of a matrix. After applying this function to an input matrix x, 
#each row of x should be a vector of unit length (meaning length 1).

In [37]:
# GRADED FUNCTION: normalizeRows

def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    x_norm = np.linalg.norm(x,ord=2,axis=1,keepdims=True)
    
    # Divide x by its norm.
    x = x/x_norm
    ### END CODE HERE ###

    return x


In [38]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [39]:
#1.5 - Broadcasting and the softmax function
#A very important concept to understand in numpy is "broadcasting". It is very useful for performing mathematical 
#operations between arrays of different shapes. For the full details on broadcasting, 
#you can read the official broadcasting documentation.

#**Exercise**: Implement a softmax function using numpy. You can think of softmax as a normalizing function used 
#when your algorithm needs to classify two or more classes. You will learn more about softmax in the second course 
#of this specialization.


In [40]:
# GRADED FUNCTION: softmax

def softmax(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (m,n).

    Argument:
    x -- A numpy matrix of shape (m,n)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (m,n)
    """
    
    ### START CODE HERE ### (≈ 3 lines of code)
    # Apply exp() element-wise to x. Use np.exp(...).
    x_exp = np.exp(x)

    # Create a vector x_sum that sums each row of x_exp. Use np.sum(..., axis = 1, keepdims = True).
    x_sum = np.sum(x_exp,axis=1,keepdims=True)
    
    # Compute softmax(x) by dividing x_exp by x_sum. It should automatically use numpy broadcasting.
    s = x_exp/x_sum

    ### END CODE HERE ###
    
    return s

In [41]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [42]:
#If you print the shapes of x_exp, x_sum and s above and rerun the assessment cell, 
#you will see that x_sum is of shape (2,1) while x_exp and s are of shape (2,5). x_exp/x_sum works due to python broadcasting.

#What you need to remember:

#np.exp(x) works for any np.array x and applies the exponential function to every coordinate
#the sigmoid function and its gradient
#image2vector is commonly used in deep learning
#numpy has efficient built-in functions
#broadcasting is extremely useful

In [43]:
#2) Vectorization
#In deep learning, you deal with very large datasets. Hence, a non-computationally-optimal function 
#can become a huge bottleneck in your algorithm and can result in a model that takes ages to run. 
#To make sure that your code is computationally efficient, you will use vectorization. For example, 
#try to tell the difference between the following implementations of the dot/outer/elementwise product.

In [44]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.0ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
 ---

In [45]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.0ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.0ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.0ms
gdot = [23.68070522 25.82744871 23.21440818]
 ----- Computation time = 0.0ms


In [46]:
#As you may have noticed, the vectorized implementation is much cleaner and more efficient. For bigger vectors/matrices, the differences in running time become even bigger.

#Note that np.dot() performs a matrix-matrix or matrix-vector multiplication. This is different from np.multiply() and the * operator (which is equivalent to .* in Matlab/Octave),
#which performs an element-wise multiplication.

In [48]:
#2.1 Implement the L1 and L2 loss functions
#Exercise: Implement the numpy vectorized version of the L1 loss. You may find the function abs(x) (absolute value of x) useful.

#Reminder:

#The loss is used to evaluate the performance of your model. The bigger your loss is, the more different your predictions ( ŷ y^ ) are from the true values ( yy ). In deep learning, you use optimization algorithms like Gradient Descent to train your model and to minimize the cost.
#L1 loss is defined as:
#L1(ŷ ,y)=∑i=0m|y(i)−ŷ (i)| # GRADED FUNCTION: L1

def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = np.sum(abs(y-yhat))
    ### END CODE HERE ###
    
    return loss


In [49]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [51]:
#Exercise: Implement the numpy vectorized version of the L2 loss. There are several way of implementing the L2 loss but you may find the function np.dot() useful. As a reminder, if  x=[x1,x2,...,xn]x=[x1,x2,...,xn] , then np.dot(x,x) =  ∑nj=0x2j∑j=0nxj2 .

#L2 loss is defined as
#L2(ŷ ,y)=∑i=0m(y(i)−ŷ (i))2

In [52]:
# GRADED FUNCTION: L2

def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = np.dot(y,y)+np.dot(yhat,yhat)-2*np.dot(yhat,y)
    ### END CODE HERE ###
    
    return loss

In [53]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.4299999999999997


In [1]:
#What to remember:

#Vectorization is very important in deep learning. It provides computational efficiency and clarity.
#You have reviewed the L1 and L2 loss.
#You are familiar with many numpy functions such as np.sum, np.dot, np.multiply, np.maximum, etc...

In [23]:
import numpy as np
X= np.random.rand(9,4,3,6)

In [24]:
print(X.shape)

(9, 4, 3, 6)


In [25]:
X.shape[0]

9

In [27]:
new_X = X.reshape(X.shape[1], -1).T
print(new_X.shape)

(162, 4)


In [28]:
new_X = X.reshape(X.shape[0], -1).T
print(new_X.shape)

(72, 9)
